# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Pew(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Pew()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPew(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Pew
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Pew
    def FireOn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(1)
def PewStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddFireOn(builder, fireOn): builder.PrependBoolSlot(0, fireOn, 0)
def PewAddFireOn(builder, fireOn):
    """This method is deprecated. Please switch to AddFireOn."""
    return AddFireOn(builder, fireOn)
def End(builder): return builder.EndObject()
def PewEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)

class PewT(object):

    # PewT
    def __init__(self):
        self.fireOn = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        pew = Pew()
        pew.Init(buf, pos)
        return cls.InitFromObj(pew)

    @classmethod
    def InitFromObj(cls, pew):
        x = PewT()
        x._UnPack(pew)
        return x

    # PewT
    def _UnPack(self, pew):
        if pew is None:
            return
        self.fireOn = pew.FireOn()

    # PewT
    def Pack(self, builder):
        Start(builder)
        AddFireOn(builder, self.fireOn)
        pew = End(builder)
        return pew
