// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PEW_H_
#define FLATBUFFERS_GENERATED_PEW_H_

#include "flatbuffers/flatbuffers.h"

struct Pew;
struct PewBuilder;
struct PewT;

struct PewT : public flatbuffers::NativeTable {
  typedef Pew TableType;
  bool fireOn = false;
};

struct Pew FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PewT NativeTableType;
  typedef PewBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIREON = 4
  };
  bool fireOn() const {
    return GetField<uint8_t>(VT_FIREON, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FIREON) &&
           verifier.EndTable();
  }
  PewT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PewT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Pew> Pack(flatbuffers::FlatBufferBuilder &_fbb, const PewT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PewBuilder {
  typedef Pew Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_fireOn(bool fireOn) {
    fbb_.AddElement<uint8_t>(Pew::VT_FIREON, static_cast<uint8_t>(fireOn), 0);
  }
  explicit PewBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Pew> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Pew>(end);
    return o;
  }
};

inline flatbuffers::Offset<Pew> CreatePew(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool fireOn = false) {
  PewBuilder builder_(_fbb);
  builder_.add_fireOn(fireOn);
  return builder_.Finish();
}

flatbuffers::Offset<Pew> CreatePew(flatbuffers::FlatBufferBuilder &_fbb, const PewT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PewT *Pew::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PewT>(new PewT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Pew::UnPackTo(PewT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = fireOn(); _o->fireOn = _e; }
}

inline flatbuffers::Offset<Pew> Pew::Pack(flatbuffers::FlatBufferBuilder &_fbb, const PewT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePew(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Pew> CreatePew(flatbuffers::FlatBufferBuilder &_fbb, const PewT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const PewT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _fireOn = _o->fireOn;
  return CreatePew(
      _fbb,
      _fireOn);
}

#endif  // FLATBUFFERS_GENERATED_PEW_H_
